import { Floor } from "floor/data";

export const floor26: Floor = {
    floorId: 26,
    title: "boss_1",
    transporterEnabled: false,
    quickShopEnabled: false,
    defaultGround: "ground",
    map: [
        [/*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 86, 86, 86, 86, 86, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 86, 141, 142, 143, 86, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 86, 144, 145, 146, 86, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 86, 147, 257, 148, 86, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 86, 86, 0, 86, 86, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 32, 32, 32, 32, 132, 32, 32, 32, 32, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 5, 5, 228, 5, 5, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 50, 228, 269, 228, 50, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 5, 5, 228, 5, 5, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 5, 32, 247, 32, 5, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, /*wall=*/18],
        [/*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18, /*wall=*/18],
    ],
    firstArriveEvents: [
        // { type: "hide", loc: [6, 2] },
        // { type: "hide", loc: [6, 3] },
        // { type: "hide", loc: [6, 4] },
        // { type: "hide", loc: [5, 2] },
        // { type: "hide", loc: [5, 3] },
        // { type: "hide", loc: [5, 4] },
        // { type: "hide", loc: [7, 2] },
        // { type: "hide", loc: [7, 3] },
        // { type: "hide", loc: [7, 4] },
        "\t[player]\b[up,player]艾达！你怎么在这？！",
        "\t[艾达,princess]{player}，我也不知道发生了什么！我的头痛的要炸开了！",
        "\t[player]\b[up,player]我就是来救你的，无论发生什么，我都不会放弃你的。",
        "\t[艾达,princess]{player}你快走，我能感觉到好像END要出来了！",
        { type: "hide", loc: [6, 6] },
        // { type: "show", loc: [6, 2] },
        // { type: "show", loc: [6, 3] },
        // { type: "show", loc: [6, 4] },
        // { type: "show", loc: [5, 2] },
        // { type: "show", loc: [5, 3] },
        // { type: "show", loc: [5, 4] },
        // { type: "show", loc: [7, 2] },
        // { type: "show", loc: [7, 3] },
        // { type: "show", loc: [7, 4] },
        "\t[END,magicDragon]{player}，你终于来了！",
        "\t[player]\b[go,player]什么？！",
        "\t[player]\b[go,player]艾达公主去哪了！",
        "\t[END,magicDragon]自我介绍一下，我叫END！",
        "\t[player]\b[go,player]（END魔王居然是一条龙吗）",
        "\t[END,magicDragon]同时也是多丽丝·妮娅·艾达（Doris Nia Eda吗）的双生一体",
        "\t[player]\b[go,player]E-N-D...D-N-E?!双生体",
        "\t[END,magicDragon]直到前些日子为止，我的意识还在沉睡。",
        "\t[END,magicDragon]艾达公主是个难缠的人，她一直压抑着我的灵魂力量，直到她某次误入这座塔的附近，我的灵魂力量才完全觉醒。",
        "\t[END,magicDragon]我马上就可以获得所有主导权了！",
        "\t[player]\b[go,player]原来如此，是这家伙影响了艾达",
        "\t[player]\b[go,player]我会打倒你，救公主出去的！",
        "\t[END,magicDragon]哈哈哈！凭你你做得到吗？",
    ],
    pointTriggerEvents: {
    },
    switchFloorEvent: {
    },
    postBattleEvent: {
        "6,4": [
            // { type: "show", loc: [6, 6] },
            { type: "hide", loc: [6, 2] },
        { type: "hide", loc: [6, 3] },
        { type: "hide", loc: [6, 4] },
        { type: "hide", loc: [5, 2] },
        { type: "hide", loc: [5, 3] },
        { type: "hide", loc: [5, 4] },
        { type: "hide", loc: [7, 2] },
        { type: "hide", loc: [7, 3] },
        { type: "hide", loc: [7, 4] },
            "\t[艾达公主,princess]{player}，谢谢你！你帮我干掉了END！我现在感觉好多了！",
            "\t[player]\b[go,player]太好了，你没事就好。",
            "\t[player]\b[go,player]这一路上遇到了好多神奇的人，是他们帮助了我，我才能打败END救下你。",
            "\t[艾达公主,princess]谢谢你，我的挚友，{player}。",
            "\t[艾达公主,princess]最后，可尼小朋友，10.3生日快乐！",
            "\t[艾达公主,princess]祝你每天开开心心~！",
            // { "type": "setValue", "name": "status:hp", "value": "status:attack+status:defense" },
            { "type": "win" },
        ]
    },
    postGetItemEvent: {},
    postOpenDoorEvent: {},
    blockCannotMoveDirections: {},
};