import { Floor } from "floor/data";

export const floor0: Floor = {
    floorId: 0,
    title: "tower_entrance",
    name: "dream_start",
    transporterEnabled: true,
    quickShopEnabled: true,
    defaultGround: "ground",
    map: [
        [20, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 20],
        [20, 13, 13, 13, 13, 20, 20, 20, 13, 13, 13, 13, 20],
        [20, 13, 13, 13, 13, 20, 87, 20, 13, 13, 13, 13, 20],
        [20, 13, 13, 13, 13, 20, 0, 20, 13, 13, 13, 13, 20],
        [20, 13, 13, 13, 13, 20, 0, 20, 13, 13, 13, 13, 20],
        [20, 13, 13, 13, 13, 20, 0, 20, 13, 13, 13, 13, 20],
        [20, 20, 20, 13, 20, 20, 81, 20, 20, 13, 20, 20, 20],
        [17, 17, 20, 20, 20, 149, 149, 0, 20, 20, 20, 17, 17],
        [17, 17, 17, 17, 20, 20, 0, 20, 20, 17, 17, 17, 17],
        [17, 17, 17, 17, 17, 20, 20, 20, 17, 17, 17, 17, 17],
        [16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 16, 16],
        [16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 16, 16, 16],
        [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
    ],
    firstArriveEvents: [
        { type: "hide", loc: [5, 7] },
        "\t[player]\b[up,player]……我昏倒了吗？",
        "\t[???,leina]\b[up,6,7]你还好吗?",
        "\t[player]\b[up,player]……你是？",
        "\t[???,leina]\b[up,6,7]我是一个魔法师。",
        "\t[player]\b[up,player]（这地方是...，对了，艾达在这个奇怪的地方吗？）",
        "\t[player]\b[up,player]请问你认识多丽丝·妮娅·艾达（Doris Nia Eda吗）？我是来救她的。",
        "\t[蕾娜,leina]\b[up,6,7]原来是公主的朋友。",
        "\t[蕾娜,leina]\b[up,6,7]我是公主的朋友——魔法师蕾娜。",
        "\t[player]\b[up,player]（公主的朋友蕾娜？为何从来没听说过这个名字）",
        "\t[player]\b[up,player] 蕾娜你好，我是{player}",
        "\t[player]\b[up,player]……我这是在哪？我的剑怎么不见了？",
        "\t[蕾娜,leina]\b[up,6,7]{player}，你好，这是终结塔！",
        "\t[蕾娜,leina]\b[up,6,7]我方才感应到有人来到塔里才过来看到你，你的剑我不知道去哪了，有可能是被塔里的怪物拿走了。",
        "\t[蕾娜,leina]\b[up,6,7]这么久来你是第一个能从塔外进来的人，不过这里处处都是怪物，你现在力量还不够，尤其是魔王END，他的力量恐怖如斯。",
        "\t[player]\b[up,player]我得救出艾达，蕾娜你能告诉我怎么才能救她？",
        "\t[蕾娜,leina]\b[up,6,7]如你所见，现在是只剩一丝灵魂力量的灵魂体，没办法直接帮你。",
        "\t[蕾娜,leina]\b[up,6,7]塔内强者为王，你需要尽快变强，才有可能打败魔王END，救出公主。",
        "\t[player]\b[up,player]嗯，我会努力的。",
        "\t[蕾娜,leina]\b[up,6,7]我有一个灵器被怪物抢走了，你如果能找回给我的话，能让你变强很多！",
        "\t[player]\b[up,player]灵器？它长什么样？",
        "\t[蕾娜,leina]\b[up,6,7]一个中心镶嵌着红色宝石的十字架灵器。",
        "\t[蕾娜,leina]\b[up,6,7]不久前，魔王END突然带怪物们占领了这座塔，并把公主和我囚禁在高层。为了躲过END的追杀，我将力量注入了灵器里，隐藏气息，只有灵魂逃了出来。能拿到灵器的话，就可以回复我的力量。",
        "\t[player]\b[up,player]原来如此（为了就出艾达，姑且相信她吧）",
        "\t[蕾娜,leina]\b[up,6,7] {player}，要记住，只有拿到灵器后，用我的魔力才可以打开21层的门。",
        "\t[player]\b[up,player]好，我会去找到灵器给你的。",
        "\t[蕾娜,leina]\b[up,6,7] {player}，我这里有些开门的钥匙，你拿着吧。",
        { type: "setValue", name: "item:yellowKey", value: "item:yellowKey+1" },
        { type: "setValue", name: "item:blueKey", value: "item:blueKey+1" },
        { type: "setValue", name: "item:redKey", value: "item:redKey+1" },
        "\t[player]\b[up,player]谢谢你，蕾娜。",
        "\t[蕾娜,leina]\b[up,6,7]前进吧，我会给你加油的！",
        "\t[蕾娜,leina]\b[up,6,7](艾达...你或许有救了)",
        { type: "move", loc: [6, 7], steps: ["left"], time: 750, immediateHide: true },
        { type: "show", loc: [5, 7] },
    ],
    pointTriggerEvents: {
        "5,7": {
            enable: false,
            data: [
                {
                    type: "if",
                    condition: "item:cross>0",
                    true: [
                        { type: "setValue", name: "flag:levelUp", value: "true" },
                        "\t[蕾娜,leina]\b[up]这是我的灵器，感谢你，{player}，我可以助你一臂之力了",
                        "\t[蕾娜,leina]\b[up]我现在将你的全属性提升1/3！\n鸡你太美！",
                        { type: "animate", name: "yongchang" },
                        { type: "animate", name: "levelup", loc: "player" },
                        { type: "setValue", name: "status:hp", value: "status:hp*4/3" },
                        { type: "setValue", name: "status:attack", value: "status:attack*4/3" },
                        { type: "setValue", name: "status:defense", value: "status:defense*4/3" },
                        "\t[蕾娜,leina]\b[up]好了，祝你成功救出艾达公主！",
                        "\t[蕾娜,leina]\b[up]等等，灵器激活后我感召到一个神秘空间，哪里的入口被打开了,我去调查一下。",
                        "\t[蕾娜,leina]\b[up]{player}，你要完事小心！",
                        // { type: "show", loc: [6, 8], floorId: 20 },
                        { type: "hide", time: 500 },
                    ],
                    false: ["\t[小精灵,leina]\b[up]有没有拿到灵器？"],
                },
            ],
        },
    },
    switchFloorEvent: {
        "6,2": { floorId: 1, stairDirection: "downFloor" },
    },
    postBattleEvent: {},
    postGetItemEvent: {},
    postOpenDoorEvent: {},
    blockCannotMoveDirections: {},
};